import os
from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional
import uvicorn
from datetime import datetime
from openai import OpenAI
from dotenv import load_dotenv

# Load biến môi trường
load_dotenv()

# Lấy API key từ biến môi trường
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    raise ValueError("OPENAI_API_KEY không được tìm thấy trong biến môi trường")

client = OpenAI(api_key=OPENAI_API_KEY)

# Đọc toàn bộ nội dung file txt
full_context = '''Mục 3: Chuyên Ngành
Chunk 1: Kinh tế phát triển (Mã ngành: 7310101)
Chuyên ngành Kinh tế phát triển, thuộc ngành Kinh tế, đào tạo cử nhân với kiến thức chuyên sâu về các vấn đề kinh tế - xã hội, chính sách công và phát triển bền vững, đạt chuẩn kiểm định AUN-QA. Chương trình cung cấp nền tảng vững chắc về các mô hình phát triển kinh tế, quản lý tài nguyên, giảm nghèo, an sinh xã hội và các giải pháp thúc đẩy tăng trưởng kinh tế bền vững. Sinh viên được trang bị kỹ năng nghiên cứu, phân tích dữ liệu kinh tế và đánh giá tác động chính sách, giúp họ hoạch định chiến lược phát triển hiệu quả. Ngoài ra, chương trình chú trọng phát triển tư duy đổi mới, cho phép sinh viên thích nghi với sự thay đổi nhanh chóng của nền kinh tế toàn cầu. Các môn học nhấn mạnh khả năng làm việc nhóm, tư duy phản biện và kỹ năng giao tiếp, chuẩn bị cho sinh viên tham gia vào môi trường làm việc đa dạng. Cơ hội nghề nghiệp của chuyên ngành này rất rộng mở, bao gồm các vị trí như chuyên viên hoạch định chính sách kinh tế - xã hội tại các cơ quan nhà nước như Bộ Kế hoạch & Đầu tư, Bộ Tài chính, hoặc UBND các cấp. Sinh viên cũng có thể làm chuyên viên quản lý dự án tại các tổ chức quốc tế như UNDP, ADB, World Bank, hoặc chuyên viên phát triển bền vững tại các tổ chức phi chính phủ như Oxfam, WWF. Ngoài ra, các vị trí nghiên cứu về kinh tế nông nghiệp, đô thị, công nghiệp hoặc giảng viên, nhà nghiên cứu tại các trường đại học và viện nghiên cứu cũng là lựa chọn tiềm năng. Chuyên ngành này đặc biệt phù hợp với những ai đam mê giải quyết các thách thức kinh tế - xã hội và đóng góp vào sự phát triển bền vững của cộng đồng. Với nền tảng kiến thức và kỹ năng được đào tạo, sinh viên tốt nghiệp có thể tự tin đảm nhận các vai trò quan trọng trong việc định hình chính sách và thúc đẩy tăng trưởng kinh tế.
________________


Chunk 2: Kinh tế đầu tư (Mã ngành: 7310101)
Chuyên ngành Kinh tế đầu tư, thuộc ngành Kinh tế, trang bị cho sinh viên kiến thức vững chắc về đầu tư, quản lý tài chính và phân tích hiệu quả dự án trong bối cảnh kinh tế hiện đại. Chương trình đào tạo tập trung vào các nguyên tắc kinh tế, chính sách đầu tư, phân tích rủi ro và kỹ năng lập kế hoạch, thực hiện các dự án đầu tư. Sinh viên được học cách đánh giá các cơ hội đầu tư, quản lý nguồn vốn và tối ưu hóa lợi nhuận trong môi trường cạnh tranh. Ngoài kiến thức chuyên môn, chương trình chú trọng phát triển các kỹ năng mềm như tư duy phản biện, làm việc nhóm, giao tiếp và trình bày báo cáo, giúp sinh viên thích nghi với môi trường làm việc năng động. Các môn học được thiết kế để cung cấp cả lý thuyết và ứng dụng thực tiễn, chuẩn bị cho sinh viên đối mặt với các thách thức thực tế. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ chuyên viên phân tích đầu tư tại các công ty chứng khoán, quỹ đầu tư, ngân hàng thương mại, đến chuyên viên quản lý rủi ro tại các ngân hàng hoặc công ty bảo hiểm. Sinh viên cũng có thể làm chuyên viên tư vấn đầu tư tại các ngân hàng lớn hoặc công ty chứng khoán, hoặc tham gia nghiên cứu kinh tế tại các trung tâm báo cáo kinh tế. Với nền tảng kiến thức toàn diện, sinh viên tốt nghiệp có khả năng đảm nhận các vai trò quan trọng trong lĩnh vực tài chính và đầu tư. Chuyên ngành này đặc biệt phù hợp với những ai yêu thích phân tích tài chính và mong muốn đóng góp vào sự phát triển của các dự án đầu tư quy mô lớn. Khả năng thích ứng với môi trường cạnh tranh cao và tư duy chiến lược là những lợi thế nổi bật mà chương trình mang lại. Sinh viên được khuyến khích phát triển tư duy sáng tạo và kỹ năng ra quyết định, đảm bảo sự thành công trong sự nghiệp tương lai.
________________


Chunk 3: Kinh tế quốc tế (Mã ngành: 7310101)
Chuyên ngành Kinh tế quốc tế, thuộc ngành Kinh tế, cung cấp cho sinh viên kiến thức chuyên sâu về hội nhập kinh tế, thương mại quốc tế, tài chính toàn cầu và chính sách kinh tế đối ngoại. Chương trình đào tạo, đặc biệt với tùy chọn bán phần tiếng Anh, trang bị nền tảng lý thuyết vững chắc và năng lực phân tích chuyên sâu về các hiệp định thương mại, logistics và chuỗi cung ứng toàn cầu. Sinh viên được rèn luyện kỹ năng giao tiếp tiếng Anh, viết báo cáo và thuyết trình quốc tế, giúp họ tự tin làm việc trong môi trường toàn cầu. Các môn học nhấn mạnh khả năng hoạch định chính sách kinh tế và tương tác hiệu quả với các đối tác quốc tế. Ngoài ra, chương trình phát triển kỹ năng mềm như tư duy phản biện và làm việc nhóm, chuẩn bị cho sinh viên thích nghi với môi trường kinh tế đa dạng. Cơ hội nghề nghiệp của chuyên ngành này rất phong phú, bao gồm các vị trí như chuyên viên thương mại quốc tế tại các tập đoàn đa quốc gia, công ty xuất nhập khẩu hoặc logistics. Sinh viên có thể làm chuyên viên phân tích thương mại tại Bộ Công Thương, Bộ Kế hoạch & Đầu tư, hoặc chuyên viên tài chính quốc tế tại các tổ chức như IMF, World Bank. Các vị trí trong lĩnh vực logistics, chuỗi cung ứng toàn cầu hoặc giảng viên, nhà nghiên cứu tại các trường đại học cũng rất triển vọng. Với tùy chọn bán phần tiếng Anh, sinh viên có lợi thế làm việc tại các cơ quan ngoại giao, tổ chức quốc tế như Liên Hợp Quốc, hoặc các NGO. Chuyên ngành này phù hợp với những ai đam mê làm việc trong môi trường quốc tế và có khả năng sử dụng ngoại ngữ tốt. Chương trình không chỉ cung cấp kiến thức mà còn xây dựng tư duy toàn cầu, giúp sinh viên sẵn sàng cho sự nghiệp trong bối cảnh hội nhập kinh tế sâu rộng.
________________


Chunk 4: Thống kê kinh tế - xã hội (Mã ngành: 7310107)
Chuyên ngành Thống kê kinh tế - xã hội, thuộc ngành Thống kê kinh tế, trang bị cho sinh viên nền tảng vững chắc về khoa học kinh tế, quản lý và phân tích dữ liệu, đáp ứng nhu cầu của môi trường kinh tế số. Chương trình đào tạo tập trung vào thống kê lý thuyết và ứng dụng, giúp sinh viên thành thạo quy trình thu thập, xử lý, phân tích và diễn giải dữ liệu một cách khoa học. Sinh viên được học cách sử dụng các công cụ thống kê hiện đại, xây dựng mô hình dự báo và tối ưu hóa quyết định, từ đó hỗ trợ doanh nghiệp đưa ra chiến lược dựa trên dữ liệu. Ngoài kiến thức chuyên môn, chương trình rèn luyện kỹ năng tư duy logic, giải quyết vấn đề và làm việc nhóm, chuẩn bị cho sinh viên thích nghi với môi trường làm việc cạnh tranh. Các môn học được thiết kế để kết hợp lý thuyết và thực hành, giúp sinh viên áp dụng kiến thức vào thực tế. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ thống kê viên trong hệ thống thống kê nhà nước đến chuyên viên nghiên cứu thị trường tại các doanh nghiệp. Sinh viên có thể làm chuyên viên phân tích kinh doanh tại các tổ chức nhà nước hoặc tư nhân, hoặc chuyên viên phân tích định lượng tài chính tại các công ty chứng khoán, ngân hàng thương mại. Các vị trí giảng viên hoặc nhà nghiên cứu tại các cơ sở đào tạo cũng là lựa chọn tiềm năng. Chuyên ngành này đặc biệt phù hợp với những ai yêu thích làm việc với dữ liệu và mong muốn đóng góp vào việc ra quyết định chiến lược. Với sự phát triển của kinh tế số, nhu cầu nhân lực trong lĩnh vực thống kê ngày càng tăng, mang lại triển vọng nghề nghiệp sáng sủa. Sinh viên tốt nghiệp có thể tự tin đảm nhận các vai trò quan trọng trong việc nâng cao hiệu quả hoạt động của tổ chức.
________________


Chunk 5: Kinh tế chính trị (Mã ngành: 7310205)
Chuyên ngành Kinh tế chính trị, thuộc ngành Quản lý Nhà nước, là chương trình đào tạo tiềm năng, cung cấp cho sinh viên năng lực hoạch định chiến lược và quản lý trong bộ máy nhà nước, tổ chức kinh doanh và các đơn vị hành chính sự nghiệp. Chương trình trang bị kiến thức sâu rộng về kinh tế, chính trị, xã hội, kết hợp với kỹ năng tổ chức, hành chính và tư duy phản biện. Sinh viên được rèn luyện phẩm chất đạo đức, ý thức tuân thủ pháp luật, cùng với kỹ năng ngoại ngữ, tin học và giao tiếp trong kinh doanh. Các môn học nhấn mạnh khả năng phân tích chính sách và quản lý nguồn lực, chuẩn bị cho sinh viên đảm nhận các vai trò lãnh đạo. Chương trình có học phí thuộc nhóm thấp nhất trong các chương trình đào tạo của Trường Đại học Kinh tế, phù hợp với nhiều đối tượng học sinh. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ cán bộ tham mưu tại các cơ quan Đảng và Nhà nước, đến chuyên viên hoạch định chính sách kinh tế - xã hội ở các cấp từ trung ương đến địa phương. Sinh viên cũng có thể làm cán bộ nghiên cứu tại các viện nghiên cứu, trường chính trị, hoặc giảng dạy các môn khoa học xã hội, kinh tế chính trị tại các trường đại học, cao đẳng. Ngoài ra, các vị trí trong doanh nghiệp quốc doanh, công ty cổ phần hoặc tổ chức khoa học - kỹ thuật cũng là lựa chọn tiềm năng. Chuyên ngành này đặc biệt phù hợp với những ai yêu thích lãnh đạo, quản lý và có tâm huyết với công việc công. Với phạm vi hoạt động nghề nghiệp rộng, bao gồm cả khu vực công và tư, sinh viên tốt nghiệp có thể phát triển sự nghiệp linh hoạt. Chương trình tích hợp tư duy vi mô và vĩ mô, giúp sinh viên sẵn sàng đóng góp vào sự phát triển của tổ chức và cộng đồng.
________________


Chunk 6: Hành chính công (Mã ngành: 7310205)
Chuyên ngành Hành chính công, thuộc ngành Quản lý Nhà nước, là chương trình đào tạo mới được triển khai từ năm 2014, mang đến cơ hội nghề nghiệp rộng mở trong cả khu vực công và tư. Chương trình trang bị cho sinh viên kiến thức chuyên sâu về quản lý hành chính, hoạch định chính sách và tổ chức bộ máy nhà nước. Sinh viên được rèn luyện kỹ năng phân tích, tư duy chiến lược và giao tiếp, cùng với phẩm chất đạo đức và ý thức tuân thủ pháp luật. Các môn học tập trung vào kỹ năng tổ chức, quản lý công việc và lãnh đạo, giúp sinh viên thích nghi với môi trường làm việc đa dạng. Với học phí hợp lý, chương trình phù hợp với những ai đam mê công việc quản lý và có tâm huyết với cộng đồng. Cơ hội nghề nghiệp của chuyên ngành này bao gồm các vị trí công chức, viên chức trong các cơ quan Đảng, Nhà nước, tổ chức đoàn thể các cấp, hoặc các đơn vị sự nghiệp công lập. Sinh viên có thể làm nhân viên hành chính trong các doanh nghiệp nhà nước hoặc tư nhân, hoặc đảm nhận vai trò cán bộ chuyên trách về tổ chức, xây dựng chính sách công. Các vị trí lãnh đạo như chủ tịch, phó chủ tịch phường/xã, hoặc trưởng/phó phòng trong các tổ chức kinh tế - xã hội cũng là triển vọng nghề nghiệp hấp dẫn. Ngoài ra, sinh viên có cơ hội trở thành cán bộ lãnh đạo cấp trung ương trong các cơ quan Đảng, Nhà nước. Chuyên ngành này đặc biệt phù hợp với những ai yêu thích đối mặt với các thách thức tổ chức và có phong cách lãnh đạo. Chương trình đào tạo mới mẻ, kết hợp lý thuyết và thực tiễn, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc cải thiện hiệu quả quản lý nhà nước và đóng góp vào sự phát triển xã hội.
________________


Chunk 7: Quản trị kinh doanh tổng quát (Mã ngành: 7340101)
Chuyên ngành Quản trị kinh doanh tổng quát, thuộc ngành Quản trị kinh doanh, đào tạo cử nhân với năng lực chuyên môn toàn diện, sẵn sàng thực hiện các công việc kinh doanh và quản trị trong các tổ chức đa dạng. Chương trình trang bị kiến thức rộng về các chức năng quản trị như marketing, tài chính, nhân sự và sản xuất, kết hợp với kỹ năng tin học, ngoại ngữ và giao tiếp kinh doanh. Sinh viên được rèn luyện tư duy chiến lược, khả năng lãnh đạo và phẩm chất doanh nhân, giúp họ thích nghi với môi trường kinh doanh thay đổi nhanh chóng. Các môn học được thiết kế dựa trên lý thuyết và mô hình thực tiễn, tăng cường kỹ năng thực hành thông qua các kỳ thực tập tại doanh nghiệp. Chương trình cũng tạo cơ hội trao đổi học thuật và học hỏi từ các quản trị viên thành công. Cơ hội nghề nghiệp của chuyên ngành này rất phong phú, từ chuyên viên kinh doanh, giám đốc bán hàng khu vực, đến chuyên viên phân tích và tư vấn quản trị kinh doanh. Sinh viên có thể làm quản trị viên tại các phòng ban chức năng như marketing, nhân sự, hoặc đảm nhận vai trò giám đốc điều hành, tổng giám đốc doanh nghiệp. Ngoài ra, nhiều sinh viên chọn tự thành lập và điều hành doanh nghiệp riêng. Chuyên ngành này phù hợp với những ai có tham vọng trở thành nhà quản lý đa năng và sáng tạo. Với nền tảng kiến thức rộng, sinh viên tốt nghiệp có thể làm việc trong mọi loại hình tổ chức, từ doanh nghiệp tư nhân đến cơ quan chính quyền và tổ chức phi lợi nhuận. Chương trình nhấn mạnh khả năng học tập suốt đời, đảm bảo sinh viên luôn cập nhật xu hướng quản trị mới nhất để đạt thành công trong sự nghiệp.
________________


Chunk 8: Quản trị tài chính (Mã ngành: 7340101)
Chuyên ngành Quản trị tài chính, thuộc ngành Quản trị kinh doanh, đào tạo cử nhân có năng lực chuyên môn trong việc quản lý tài chính doanh nghiệp, từ lập báo cáo tài chính đến phân tích và hoạch định tài chính. Chương trình trang bị kiến thức sâu rộng về chính sách thuế, quản trị tín dụng, ngân quỹ, bảo hiểm và rủi ro, cùng với kỹ năng dự toán ngân sách và đấu thầu. Sinh viên được rèn luyện tư duy phân tích, khả năng ra quyết định và kỹ năng giao tiếp kinh doanh, giúp họ thích nghi với môi trường làm việc cạnh tranh. Các môn học kết hợp lý thuyết và thực hành, chuẩn bị cho sinh viên đảm nhận các vai trò quan trọng trong lĩnh vực tài chính. Chương trình cũng nhấn mạnh ý thức đạo đức nghề nghiệp và khả năng học tập suốt đời. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ nhà quản trị tài chính trong các doanh nghiệp, chịu trách nhiệm lập kế hoạch tài chính và quản trị rủi ro, đến các vị trí trong tổ chức tài chính như quản trị tín dụng hoặc phát triển sản phẩm tài chính. Sinh viên có thể làm việc tại các cơ quan chính phủ, tham gia quản lý ngân sách, đấu thầu hoặc tài trợ. Chuyên ngành này phù hợp với những ai yêu thích làm việc với số liệu và có khả năng tư duy chiến lược. Với nhu cầu ngày càng cao về quản trị tài chính, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa trong các doanh nghiệp, tổ chức tài chính và cơ quan nhà nước. Chương trình đào tạo cung cấp nền tảng vững chắc, giúp sinh viên tự tin đảm nhận các vai trò lãnh đạo tài chính hoặc tư vấn trong tương lai. Khả năng ứng dụng kiến thức vào thực tiễn là lợi thế nổi bật, đảm bảo sinh viên sẵn sàng cho sự nghiệp thành công.
________________


Chunk 9: Quản trị chuỗi cung ứng & logistics (Mã ngành: 7340101)
Chuyên ngành Quản trị chuỗi cung ứng & logistics, thuộc ngành Quản trị kinh doanh, đào tạo cử nhân có năng lực quản trị các hoạt động chuỗi cung ứng trong môi trường kinh doanh toàn cầu. Chương trình cung cấp kiến thức chuyên sâu về quản trị sản xuất, vận tải, kho bãi và phân phối, kết hợp với kỹ năng phân tích và hoạch định nhu cầu. Sinh viên được rèn luyện khả năng sử dụng công nghệ logistics tiên tiến và tư duy chiến lược, giúp họ tối ưu hóa quy trình cung ứng. Các môn học được thiết kế dựa trên ứng dụng thực tiễn, với cơ hội thực tập và học hỏi từ các doanh nghiệp lớn. Chương trình cũng nhấn mạnh kỹ năng giao tiếp, làm việc nhóm và khả năng thích nghi với sự thay đổi nhanh chóng. Cơ hội nghề nghiệp của chuyên ngành này rất phong phú, từ nhân viên phân tích nhu cầu, hoạch định sản xuất, đến quản trị kho bãi và vận tải trong các doanh nghiệp đa quốc gia. Sau 5–10 năm, sinh viên có thể thăng tiến lên các vị trí như nhà quản trị chuỗi cung ứng, giám đốc sản xuất hoặc quản lý vùng. Chuyên ngành này phù hợp với những ai yêu thích làm việc trong môi trường năng động và có khả năng tổ chức tốt. Với sự phát triển của thương mại điện tử và logistics, nhu cầu nhân lực trong lĩnh vực này ngày càng tăng. Sinh viên tốt nghiệp có thể làm việc tại các tập đoàn lớn hoặc khởi nghiệp trong lĩnh vực logistics. Chương trình đào tạo cung cấp nền tảng kiến thức toàn diện, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc cải thiện hiệu quả chuỗi cung ứng và nâng cao năng lực cạnh tranh của doanh nghiệp.
________________


Chunk 10: Kinh doanh số (Mã ngành: 7340101)
Chuyên ngành Kinh doanh số, thuộc ngành Quản trị kinh doanh, là chương trình liên ngành kết hợp khoa học quản trị với công nghệ 4.0, đào tạo cử nhân có khả năng quản trị doanh nghiệp trong môi trường số. Chương trình cung cấp kiến thức nền về quản trị kinh doanh và chuyên sâu về các công nghệ số như trí tuệ nhân tạo, dữ liệu lớn và thương mại điện tử. Sinh viên được rèn luyện kỹ năng phân tích, tư duy sáng tạo và khả năng ứng dụng công nghệ vào quản trị. Các môn học nhấn mạnh thực hành, với các dự án thực tế và kỳ thực tập tại doanh nghiệp, giúp sinh viên tiếp cận môi trường làm việc chuyên nghiệp. Chương trình cũng phát triển kỹ năng mềm như giao tiếp và làm việc nhóm, chuẩn bị cho sinh viên thích nghi với xu hướng chuyển đổi số. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ nhà quản trị trong các doanh nghiệp số đến chuyên viên chuyển đổi số trong các tổ chức truyền thống. Sinh viên có thể làm việc trong các lĩnh vực công nghệ, giáo dục, hoặc hành chính, giúp doanh nghiệp nâng cao hiệu quả kinh doanh thông qua ứng dụng số. Chuyên ngành này phù hợp với những ai đam mê công nghệ và muốn dẫn đầu trong thời đại số hóa. Với sự kết hợp giữa lý thuyết và thực tiễn, chương trình mang lại lợi thế cạnh tranh cho sinh viên trên thị trường lao động. Sinh viên tốt nghiệp có thể đảm nhận các vai trò quan trọng trong việc phát triển chiến lược số và quản trị doanh nghiệp hiện đại. Chương trình đào tạo được thiết kế theo mô hình tiên tiến, lấy cảm hứng từ các trường đại học Âu Mỹ, đảm bảo sinh viên sẵn sàng cho sự nghiệp toàn cầu.
________________


Chunk 11: Quản trị marketing (Mã ngành: 7340115)
Chuyên ngành Quản trị marketing, thuộc ngành Marketing, đào tạo cử nhân với kiến thức chuyên sâu và kỹ năng thực tiễn, đáp ứng nhu cầu nhân lực trong nước và quốc tế. Chương trình cung cấp nền tảng vững chắc về hành vi khách hàng, nghiên cứu thị trường, quản trị thương hiệu và hoạch định kế hoạch marketing trong thời đại số. Sinh viên được rèn luyện tư duy chiến lược, khả năng sáng tạo và kỹ năng phân tích, giúp họ quản trị các hoạt động marketing hiệu quả. Các môn học kết hợp lý thuyết và thực hành, với các dự án thực tế và kỳ thực tập tại doanh nghiệp. Chương trình cũng nhấn mạnh kỹ năng giao tiếp, làm việc nhóm và khả năng thích nghi với môi trường đa văn hóa. Cơ hội nghề nghiệp của chuyên ngành này rất phong phú, từ chuyên viên marketing, phát triển sản phẩm, đến trưởng phòng marketing hoặc giám đốc thương hiệu tại các doanh nghiệp. Sinh viên có thể làm việc tại các công ty cung ứng dịch vụ marketing (agency), đảm nhận vai trò xây dựng chiến lược quảng cáo và phát triển thương hiệu. Ngoài ra, chương trình trang bị kiến thức khởi nghiệp, giúp sinh viên tự mở công ty hoặc tiếp tục học cao học tại các trường trong và ngoài nước. Chuyên ngành này phù hợp với những ai đam mê sáng tạo và muốn làm việc trong lĩnh vực năng động. Với sự phát triển của marketing số, nhu cầu nhân lực trong ngành ngày càng tăng, mang lại triển vọng nghề nghiệp sáng sủa. Sinh viên tốt nghiệp có thể tự tin đảm nhận các vai trò quan trọng trong việc xây dựng và phát triển thương hiệu, nâng cao giá trị doanh nghiệp trên thị trường.
________________


Chunk 12: Truyền thông marketing (Mã ngành: 7340115)
Chuyên ngành Truyền thông marketing, thuộc ngành Marketing, đào tạo cử nhân với kiến thức chuyên sâu về quản trị truyền thông, quảng cáo và quan hệ công chúng, đáp ứng nhu cầu nhân lực trong môi trường toàn cầu hóa. Chương trình cung cấp nền tảng vững chắc về hành vi khách hàng, nghiên cứu thị trường và xây dựng chiến lược truyền thông tích hợp. Sinh viên được rèn luyện kỹ năng giao tiếp, làm việc nhóm và phân tích, giúp họ tổ chức sự kiện, quản trị thương hiệu và thực thi các chiến dịch marketing hiệu quả. Các môn học kết hợp lý thuyết và thực hành, với các dự án thực tế và cơ hội thực tập tại doanh nghiệp. Chương trình cũng nhấn mạnh khả năng thích nghi với môi trường đa văn hóa và xu hướng số hóa. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ chuyên viên quan hệ công chúng, tổ chức sự kiện, đến giám đốc truyền thông hoặc giám đốc thương hiệu tại các doanh nghiệp. Sinh viên có thể làm việc tại các công ty cung ứng dịch vụ marketing, đảm nhận vai trò xây dựng chiến dịch quảng cáo và quản trị truyền thông. Ngoài ra, các vị trí trong cơ quan nhà nước hoặc tổ chức phi chính phủ, phụ trách tổ chức sự kiện và chiến lược truyền thông, cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai yêu thích sáng tạo và giao tiếp. Chương trình trang bị kiến thức khởi nghiệp và học cao học, giúp sinh viên phát triển sự nghiệp linh hoạt. Với nhu cầu ngày càng cao về truyền thông chuyên nghiệp, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa, sẵn sàng đảm nhận các vai trò quan trọng trong việc nâng cao hình ảnh và giá trị của tổ chức.
________________


Chunk 13: Marketing số (Mã ngành: 7340115)
Chuyên ngành Marketing số, thuộc ngành Marketing, đào tạo cử nhân với kiến thức chuyên sâu về quản trị marketing trong môi trường số, đáp ứng nhu cầu nhân lực trong thời đại công nghệ 4.0. Chương trình cung cấp nền tảng vững chắc về hành vi khách hàng, nghiên cứu thị trường và các kỹ năng như marketing đa kênh, marketing nội dung, và quản trị truyền thông xã hội. Sinh viên được rèn luyện khả năng phân tích dữ liệu, tư duy sáng tạo và kỹ năng giao tiếp, giúp họ thực thi các chiến dịch marketing hiệu quả. Các môn học nhấn mạnh thực hành, với các dự án thực tế và kỳ thực tập tại doanh nghiệp. Chương trình cũng phát triển khả năng thích nghi với môi trường đa văn hóa và xu hướng số hóa toàn cầu. Cơ hội nghề nghiệp của chuyên ngành này rất phong phú, từ chuyên viên quản lý truyền thông số, phát triển kênh bán hàng trực tuyến, đến giám đốc digital marketing hoặc trưởng phòng SEO. Sinh viên có thể làm việc tại các công ty cung ứng dịch vụ marketing, đảm nhận vai trò xây dựng chiến dịch truyền thông số và phân tích dữ liệu. Các vị trí trong cơ quan nhà nước hoặc tổ chức phi chính phủ, phụ trách chiến lược kỹ thuật số, cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai đam mê công nghệ và sáng tạo. Chương trình trang bị kiến thức khởi nghiệp và học cao học, giúp sinh viên phát triển sự nghiệp linh hoạt. Với sự bùng nổ của thương mại điện tử, nhu cầu nhân lực trong lĩnh vực marketing số ngày càng tăng, mang lại triển vọng nghề nghiệp sáng sủa. Sinh viên tốt nghiệp có thể tự tin đảm nhận các vai trò quan trọng trong việc tối ưu hóa chiến lược marketing và nâng cao hiệu quả kinh doanh.
________________


Chunk 14: Ngoại thương (Mã ngành: 7340120)
Chuyên ngành Ngoại thương, thuộc ngành Kinh doanh Quốc tế, với hơn 30 năm đào tạo, cung cấp cho sinh viên kiến thức chuyên sâu về kinh doanh quốc tế, quản trị tài chính và chuỗi cung ứng toàn cầu, đạt chuẩn kiểm định AUN-QA. Chương trình có hai hình thức đào tạo: hoàn toàn bằng tiếng Việt hoặc tiếng Anh, kết hợp lý thuyết và thực hành để chuẩn bị cho sinh viên cạnh tranh trên thị trường lao động quốc tế. Sinh viên được trang bị kỹ năng đàm phán, quản lý hợp đồng, và nghiên cứu thị trường toàn cầu, cùng với khả năng sử dụng ngoại ngữ thành thạo. Các môn học nhấn mạnh tư duy năng động và công nghệ số, giúp sinh viên tiếp cận môi trường kinh doanh hiện đại. Chương trình cũng tạo cơ hội giao lưu học thuật và thực tập tại các doanh nghiệp quốc tế. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ chuyên viên xuất nhập khẩu, quản lý vận chuyển hàng hóa, đến chuyên viên kinh doanh quốc tế tại các công ty đa quốc gia. Sinh viên có thể làm chuyên viên logistics, thanh toán quốc tế hoặc marketing quốc tế, hoặc đảm nhận vai trò quản lý tại các công ty xuất nhập khẩu. Các vị trí tại tổ chức thương mại, phòng thương mại, hoặc khu thương mại tự do Đà Nẵng cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai đam mê làm việc trong môi trường toàn cầu và có kỹ năng ngoại ngữ tốt. Với nền tảng kiến thức vững chắc, sinh viên tốt nghiệp có thể tự tin phát triển sự nghiệp trong các lĩnh vực thương mại, đầu tư và logistics quốc tế. Chương trình liên tục cập nhật theo tiêu chuẩn quốc tế, đảm bảo sinh viên sẵn sàng cho các cơ hội nghề nghiệp tại trung tâm tài chính và khu thương mại tự do.
________________


Chunk 15: Kinh doanh giao nhận và vận tải quốc tế (Mã ngành: 7340120)
Chuyên ngành Kinh doanh giao nhận và vận tải quốc tế, thuộc ngành Kinh doanh Quốc tế, đào tạo cử nhân với kiến thức chuyên sâu về quản trị vận tải, kho bãi, nghiệp vụ hải quan và kinh doanh xuất nhập khẩu, đạt chuẩn kiểm định AUN-QA. Chương trình có hai hình thức đào tạo: hoàn toàn bằng tiếng Việt hoặc bán phần tiếng Anh, kết hợp lý thuyết và thực hành để chuẩn bị cho sinh viên làm việc trong môi trường toàn cầu. Sinh viên được trang bị kỹ năng sử dụng công nghệ logistics tiên tiến, phân tích chuỗi cung ứng và quản lý vận tải quốc tế. Các môn học nhấn mạnh ứng dụng thực tiễn, với các chuyến thực tế và kỳ thực tập tại các công ty logistics. Chương trình cũng phát triển kỹ năng giao tiếp, tư duy chiến lược và khả năng thích nghi với xu hướng công nghệ. Cơ hội nghề nghiệp của chuyên ngành này rất phong phú, từ nhân viên tại các hãng vận tải, công ty logistics, đến chuyên viên tại các doanh nghiệp xuất nhập khẩu và tập đoàn đa quốc gia. Sinh viên có thể làm việc tại cơ quan hải quan, tổ chức xúc tiến thương mại, hoặc các viện nghiên cứu về logistics. Các vị trí tại khu thương mại tự do Đà Nẵng cũng là triển vọng hấp dẫn. Ngoài ra, sinh viên có thể khởi nghiệp trong lĩnh vực giao nhận và vận tải quốc tế. Chuyên ngành này phù hợp với những ai yêu thích làm việc trong môi trường năng động và có khả năng tổ chức tốt. Với sự phát triển của thương mại toàn cầu, nhu cầu nhân lực trong lĩnh vực này ngày càng tăng. Chương trình đào tạo cung cấp nền tảng vững chắc, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc tối ưu hóa chuỗi cung ứng và nâng cao hiệu quả kinh doanh quốc tế.
________________


Chunk 16: Quản trị kinh doanh thương mại (Mã ngành: 7340121)
Chuyên ngành Quản trị kinh doanh thương mại, thuộc ngành Kinh doanh Thương mại, đào tạo cử nhân với kiến thức toàn diện về quản trị và tổ chức hoạt động thương mại, đáp ứng nhu cầu phát triển mạnh mẽ của lĩnh vực này. Chương trình cung cấp nền tảng vững chắc về kinh doanh, marketing và xuất nhập khẩu, kết hợp với kỹ năng phân tích thị trường và chăm sóc khách hàng. Sinh viên được rèn luyện tư duy chiến lược, khả năng tổ chức và kỹ năng giao tiếp, giúp họ quản lý hiệu quả các hoạt động thương mại. Các môn học nhấn mạnh ứng dụng thực tiễn, với các kỳ thực tập và học hỏi từ các chuyên gia trong ngành. Chương trình cũng chú trọng phát triển đạo đức nghề nghiệp và năng lực học tập suốt đời. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ chuyên viên tổ chức kinh doanh, chuyên viên sales, đến trưởng cửa hàng bán lẻ hoặc giám đốc bán hàng khu vực. Sinh viên có thể làm việc tại các công ty thương mại, xuất nhập khẩu, siêu thị, hoặc các cơ quan như sở công thương. Các vị trí tại tổ chức quốc tế hoặc phòng thương mại cũng là lựa chọn tiềm năng. Sau 5–10 năm, sinh viên có thể thăng tiến lên các vị trí quản lý cao như trưởng phòng kinh doanh hoặc giám đốc khu vực. Chuyên ngành này phù hợp với những ai yêu thích làm việc trong môi trường năng động và có kỹ năng giao tiếp tốt. Chương trình trang bị kiến thức khởi nghiệp và học cao học, giúp sinh viên phát triển sự nghiệp linh hoạt. Với sự phát triển của thương mại toàn cầu, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa, sẵn sàng đảm nhận các vai trò quan trọng trong việc nâng cao hiệu quả kinh doanh và mở rộng thị trường.
________________


Chunk 17: Thương mại điện tử (Mã ngành: 7340122)
Chuyên ngành Thương mại điện tử, thuộc ngành Thương mại điện tử, đào tạo cử nhân với kiến thức chuyên sâu về kinh doanh trực tuyến, quản trị hệ thống số và phân tích thị trường, đáp ứng xu hướng phát triển của kinh tế số. Chương trình cung cấp nền tảng vững chắc về công nghệ số, marketing điện tử và quản lý dự án thương mại điện tử. Sinh viên được rèn luyện kỹ năng phân tích dữ liệu, tư duy sáng tạo và khả năng ứng dụng công nghệ vào kinh doanh. Các môn học kết hợp lý thuyết và thực hành, với các dự án thực tế và kỳ thực tập tại doanh nghiệp. Chương trình cũng nhấn mạnh kỹ năng giao tiếp, làm việc nhóm và khả năng thích nghi với môi trường số hóa. Cơ hội nghề nghiệp của chuyên ngành này rất phong phú, từ chuyên viên quản trị thương mại điện tử, quản lý dự án phát triển kênh bán hàng trực tuyến, đến chuyên viên phân tích thị trường tại các công ty thương mại - dịch vụ. Sinh viên có thể làm việc tại các cơ quan xúc tiến thương mại điện tử, tổ chức tư vấn giải pháp công nghệ, hoặc các viện nghiên cứu. Ngoài ra, nhiều sinh viên chọn khởi nghiệp sáng tạo trong lĩnh vực thương mại điện tử. Sau 5–10 năm, sinh viên có thể thăng tiến lên các vị trí như trưởng phòng kinh doanh hoặc giám đốc khu vực. Chuyên ngành này phù hợp với những ai đam mê công nghệ và kinh doanh trực tuyến. Chương trình trang bị kiến thức học cao học và phát triển sự nghiệp linh hoạt. Với sự bùng nổ của thương mại điện tử, nhu cầu nhân lực trong ngành ngày càng tăng, mang lại triển vọng nghề nghiệp sáng sủa. Sinh viên tốt nghiệp có thể tự tin đảm nhận các vai trò quan trọng trong việc xây dựng và quản lý hệ thống kinh doanh trực tuyến.
________________


Chunk 18: Ngân hàng (Mã ngành: 7340201)
Chuyên ngành Ngân hàng, thuộc ngành Tài chính - Ngân hàng, đào tạo cử nhân với kiến thức chuyên sâu về tài chính, ngân hàng và quản trị rủi ro, đáp ứng nhu cầu của môi trường kinh doanh toàn cầu. Chương trình kết hợp lý thuyết và thực hành, trang bị kỹ năng phân tích, hoạch định chính sách và tư duy chiến lược. Sinh viên được rèn luyện khả năng sử dụng công nghệ tài chính, giao tiếp kinh doanh và thích nghi với xu hướng quốc tế. Các môn học nhấn mạnh quản trị tín dụng, thanh toán quốc tế và quan hệ khách hàng, với tùy chọn bán phần tiếng Anh để tiếp cận tài liệu quốc tế. Chương trình cũng chú trọng đạo đức nghề nghiệp và năng lực học tập suốt đời. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ chuyên viên tín dụng, giao dịch viên, đến chuyên viên thẩm định tài sản tại các ngân hàng thương mại. Sinh viên có thể làm việc tại các công ty tài chính, quỹ đầu tư, hoặc đảm nhận vai trò phân tích tài chính trong các tập đoàn đa quốc gia. Các vị trí tại cơ quan nhà nước như Ngân hàng Nhà nước, cơ quan thuế, hoặc nghiên cứu, giảng dạy tại các trường đại học cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai yêu thích làm việc với số liệu và có tư duy logic. Với sự phát triển của ngành tài chính, nhu cầu nhân lực trong lĩnh vực ngân hàng ngày càng tăng. Sinh viên tốt nghiệp có thể khởi nghiệp trong lĩnh vực tài chính hoặc đảm nhận các vai trò lãnh đạo trong tương lai. Chương trình đào tạo hiện đại, kết hợp phương pháp tiên tiến, giúp sinh viên sẵn sàng cho sự nghiệp tại các trung tâm tài chính lớn trong khu vực và thế giới.
________________


Chunk 19: Tài chính công (Mã ngành: 7340201)
Chuyên ngành Tài chính công, thuộc ngành Tài chính - Ngân hàng, đào tạo cử nhân với kiến thức chuyên sâu về quản lý tài chính trong khu vực công, từ hoạch định chính sách đến tác nghiệp. Chương trình cung cấp nền tảng vững chắc về tài chính, thuế, ngân sách và quản lý vốn nhà nước, kết hợp với kỹ năng phân tích và ra quyết định. Sinh viên được rèn luyện phẩm chất đạo đức, ý thức tuân thủ pháp luật, cùng với kỹ năng tin học, ngoại ngữ và giao tiếp kinh doanh. Các môn học nhấn mạnh ứng dụng thực tiễn, chuẩn bị cho sinh viên làm việc trong các cơ quan nhà nước và tổ chức tài chính. Chương trình cũng khuyến khích khả năng học tập suốt đời để thích nghi với môi trường thay đổi nhanh. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ chuyên viên tại các cơ quan như Thuế, Hải quan, Kho bạc Nhà nước, đến các vị trí trong Ngân hàng Nhà nước và tổ chức tài chính phi lợi nhuận. Sinh viên có thể làm việc tại các công ty tư vấn tài chính, thuế, hoặc các doanh nghiệp nhà nước quản lý vốn đầu tư. Các vị trí trong ngân hàng thương mại, công ty bảo hiểm, hoặc quỹ đầu tư cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai yêu thích làm việc trong khu vực công và có khả năng tư duy chiến lược. Với nhu cầu ngày càng cao về quản lý tài chính công, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa. Chương trình đào tạo cung cấp nền tảng vững chắc, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc quản lý nguồn lực tài chính quốc gia.
________________


Chunk 20: Tài chính doanh nghiệp (Mã ngành: 7340201)
Chuyên ngành Tài chính doanh nghiệp, thuộc ngành Tài chính - Ngân hàng, đào tạo cử nhân với kiến thức toàn diện về thị trường tài chính, quản lý tài chính doanh nghiệp và các định chế tài chính. Chương trình cung cấp nền tảng vững chắc về kế toán, tài chính quốc tế, kiểm toán và nghiệp vụ ngân hàng, kết hợp với kỹ năng phân tích và hoạch định tài chính. Sinh viên được rèn luyện tư duy logic, khả năng ra quyết định và kỹ năng giao tiếp, giúp họ quản lý hiệu quả các hoạt động tài chính. Các môn học nhấn mạnh ứng dụng thực tiễn, chuẩn bị cho sinh viên làm việc trong môi trường cạnh tranh. Chương trình cũng chú trọng đạo đức nghề nghiệp và khả năng thích nghi với xu hướng toàn cầu. Cơ hội nghề nghiệp của chuyên ngành này rất phong phú, từ chuyên viên tài chính, thực hiện các nghiệp vụ tài chính, đến nhà quản lý hoặc tư vấn tài chính tại các doanh nghiệp. Sinh viên có thể làm việc tại các tổ chức cung ứng dịch vụ tài chính, định chế tài chính trong và ngoài nước, hoặc các viện nghiên cứu và trường đại học. Chuyên ngành này phù hợp với những ai yêu thích làm việc với số liệu và có khả năng tư duy chiến lược. Với sự phát triển của nền kinh tế, nhu cầu nhân lực trong lĩnh vực tài chính doanh nghiệp ngày càng tăng. Sinh viên tốt nghiệp có thể đảm nhận các vai trò quan trọng trong việc tối ưu hóa nguồn lực tài chính và nâng cao giá trị doanh nghiệp. Chương trình đào tạo cung cấp nền tảng kiến thức đa dạng, giúp sinh viên sẵn sàng cho sự nghiệp thành công trong môi trường kinh doanh năng động.
________________


Chunk 21: Công nghệ tài chính (Mã ngành: 7340205)
Chuyên ngành Công nghệ tài chính, thuộc ngành Công nghệ tài chính, đào tạo cử nhân với kiến thức chuyên sâu về tài chính và ứng dụng công nghệ trong bối cảnh kinh tế số và cách mạng công nghiệp 4.0. Chương trình cung cấp nền tảng vững chắc về tài chính, kết hợp với các công nghệ như trí tuệ nhân tạo, blockchain và dữ liệu lớn. Sinh viên được rèn luyện kỹ năng phân tích dữ liệu, phát triển sản phẩm tài chính và quản trị hệ thống số. Các môn học nhấn mạnh ứng dụng thực tiễn, với các dự án thực tế và kỳ thực tập tại doanh nghiệp. Chương trình cũng phát triển tư duy sáng tạo và khả năng thích nghi với các đổi mới công nghệ. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ chuyên viên phát triển sản phẩm fintech, phân tích dữ liệu tài chính, đến quản lý nền tảng số hóa tại các công ty fintech và định chế tài chính. Sinh viên có thể làm việc tại các cơ quan nhà nước, quản lý phát triển kinh tế số, hoặc khởi nghiệp trong lĩnh vực fintech. Các vị trí giảng dạy và nghiên cứu tại các trường đại học cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai đam mê công nghệ và tài chính. Với sự phát triển của kinh tế số, nhu cầu nhân lực trong lĩnh vực công nghệ tài chính ngày càng tăng, mang lại triển vọng nghề nghiệp sáng sủa. Chương trình đào tạo cung cấp nền tảng kiến thức hiện đại, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc đổi mới và phát triển các dịch vụ tài chính.
________________


Chunk 22: Kế toán (Mã ngành: 7340301)
Chuyên ngành Kế toán, thuộc ngành Kế toán, đào tạo cử nhân với năng lực chuyên môn trong phân tích tài chính, lập báo cáo kế toán và quản lý ngân sách, đạt chuẩn kiểm định AUN-QA. Chương trình tích hợp chứng chỉ nghề nghiệp quốc tế ICAEW, cung cấp kiến thức chuyên sâu về kế toán, thuế và kiểm toán. Sinh viên được rèn luyện kỹ năng sử dụng phần mềm kế toán, phân tích dữ liệu và giao tiếp kinh doanh, giúp họ làm việc hiệu quả trong môi trường toàn cầu. Các môn học kết hợp lý thuyết và thực hành, với phương pháp giảng dạy hiện đại như Blended Learning. Chương trình cũng nhấn mạnh đạo đức nghề nghiệp và khả năng học tập suốt đời. Cơ hội nghề nghiệp của chuyên ngành này rất phong phú, từ kế toán viên, nhân viên phân tích tài chính, đến kế toán trưởng hoặc giám đốc tài chính tại các doanh nghiệp trong và ngoài nước. Sinh viên có thể làm việc tại các công ty Big4, cơ quan nhà nước, hoặc tổ chức phi chính phủ. Các vị trí tại trung tâm tài chính quốc tế và khu thương mại tự do Đà Nẵng cũng là triển vọng hấp dẫn. Chuyên ngành này phù hợp với những ai yêu thích làm việc với số liệu và có tư duy logic. Với nhu cầu cao về nhân lực kế toán chuyên nghiệp, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa. Chương trình đào tạo tiên tiến, kết hợp công nghệ thông tin và trí tuệ nhân tạo, giúp sinh viên sẵn sàng cho sự nghiệp trong môi trường kinh doanh năng động. Sinh viên tốt nghiệp có thể tiếp tục học cao học hoặc đảm nhận các vai trò lãnh đạo trong lĩnh vực tài chính và kế toán.
________________


Chunk 23: Kiểm toán (Mã ngành: 7340302)
Chuyên ngành Kiểm toán, thuộc ngành Kiểm toán, đào tạo cử nhân với kiến thức chuyên sâu về kiểm toán, kế toán, tài chính và kiểm soát nội bộ, đạt chuẩn kiểm định AUN-QA. Chương trình tích hợp chứng chỉ quốc tế như ACCA, CPA và ICAEW, cung cấp nền tảng vững chắc về phân tích tài chính và quản lý rủi ro. Sinh viên được rèn luyện kỹ năng sử dụng công nghệ, giao tiếp kinh doanh và tư duy phân tích, giúp họ làm việc hiệu quả trong môi trường toàn cầu. Các môn học nhấn mạnh ứng dụng thực tiễn, với các kỳ thực tập và chương trình trao đổi quốc tế. Chương trình cũng chú trọng đạo đức nghề nghiệp và khả năng thích nghi với xu hướng kinh doanh. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ kiểm toán viên tại các công ty kiểm toán độc lập, kiểm toán nhà nước, đến kiểm soát nội bộ trong các doanh nghiệp. Sinh viên có thể làm việc tại các công ty Big4, ngân hàng, hoặc cung cấp dịch vụ tư vấn thuế và định giá doanh nghiệp. Các vị trí tại trung tâm tài chính quốc tế Đà Nẵng cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai yêu thích làm việc với số liệu và có khả năng tư duy logic. Với nhu cầu cao về nhân lực kiểm toán, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa. Chương trình đào tạo được giảng dạy bởi đội ngũ giảng viên quốc tế, giúp sinh viên sẵn sàng cho sự nghiệp trong các tổ chức đa quốc gia. Sinh viên tốt nghiệp có thể tiếp tục học cao học hoặc đảm nhận các vai trò lãnh đạo trong lĩnh vực tài chính và kiểm toán.
________________


Chunk 24: Quản trị nguồn nhân lực (Mã ngành: 7340404)
Chuyên ngành Quản trị nguồn nhân lực, thuộc ngành Quản trị nhân lực, đào tạo cử nhân với kiến thức chuyên sâu về quản lý con người và tổ chức, đáp ứng nhu cầu nhân lực trong môi trường kinh doanh năng động. Chương trình cung cấp nền tảng vững chắc về tuyển dụng, đào tạo, đánh giá thành tích, tiền lương và bảo hiểm xã hội. Sinh viên được rèn luyện kỹ năng phân tích, tư duy chiến lược và giao tiếp, giúp họ thiết kế và triển khai các chính sách nhân sự hiệu quả. Các môn học nhấn mạnh ứng dụng thực tiễn, chuẩn bị cho sinh viên đảm nhận các vai trò quản lý nguồn lực. Chương trình cũng chú trọng đạo đức nghề nghiệp và khả năng học tập suốt đời. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ chuyên viên tuyển dụng, đào tạo, đến quản lý nhân sự trong các công ty và tổ chức chính quyền. Sinh viên có thể làm chuyên viên tư vấn nghề nghiệp tại các tổ chức dịch vụ việc làm hoặc quản lý lao động. Sau 3–5 năm, sinh viên có thể thăng tiến lên trưởng phòng nhân sự, và sau 7–10 năm, đảm nhận vai trò giám đốc nguồn nhân lực. Chuyên ngành này phù hợp với những ai yêu thích làm việc với con người và có khả năng tổ chức tốt. Với nhu cầu ngày càng cao về quản trị nhân sự chuyên nghiệp, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa. Chương trình đào tạo cung cấp nền tảng kiến thức toàn diện, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc xây dựng và phát triển nguồn nhân lực, tạo lợi thế cạnh tranh cho tổ chức.
________________


Chunk 25: Tin học quản lý (Mã ngành: 7340405)
Chuyên ngành Tin học quản lý, thuộc ngành Hệ thống thông tin quản lý, đào tạo cử nhân với kiến thức nền tảng về kinh tế, quản trị kinh doanh và công nghệ thông tin, đáp ứng nhu cầu chuyển đổi số. Chương trình cung cấp kỹ năng phân tích, thiết kế và tích hợp hệ thống thông tin vào các tiến trình quản lý thông minh. Sinh viên được rèn luyện khả năng phát triển phần mềm, quản trị dự án CNTT và tư vấn giải pháp công nghệ. Các môn học nhấn mạnh ứng dụng thực tiễn, với các kỳ thực tập và tham quan thực tế tại doanh nghiệp từ năm thứ nhất. Chương trình cũng phát triển kỹ năng giao tiếp, làm việc nhóm và khả năng thích nghi với xu hướng công nghệ. Cơ hội nghề nghiệp của chuyên ngành này rất phong phú, từ phân tích và phát triển hệ thống thông tin, đến kinh doanh và tư vấn giải pháp CNTT. Sinh viên có thể làm việc tại các doanh nghiệp lớn, đảm nhận vai trò quản trị hệ thống hoặc kiểm thử phần mềm. Các vị trí giảng dạy tại các trường đại học hoặc làm việc tại các công ty quốc tế cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai yêu thích công nghệ và quản lý. Với nhu cầu cao về nhân lực CNTT, 95% sinh viên có việc làm trong 6 tháng sau tốt nghiệp, trong đó 92,3% làm đúng ngành. Chương trình đào tạo được thiết kế đặc thù cho doanh nghiệp, với sự tham gia của các chuyên gia từ các công ty lớn, giúp sinh viên sẵn sàng cho sự nghiệp trong thời đại công nghiệp 4.0.
________________


Chunk 26: Quản trị hệ thống thông tin (Mã ngành: 7340405)
Chuyên ngành Quản trị hệ thống thông tin, thuộc ngành Hệ thống thông tin quản lý, đào tạo cử nhân với kiến thức chuyên sâu về quản trị kinh doanh, hệ thống thông tin và phân tích quy trình nghiệp vụ, đáp ứng nhu cầu chuyển đổi số. Chương trình cung cấp kỹ năng thiết kế, tích hợp và quản trị hệ thống thông tin, cùng với khả năng tư vấn giải pháp CNTT. Sinh viên được rèn luyện tư duy phân tích, quản trị dự án và bảo mật thông tin, giúp họ tối ưu hóa hoạt động kinh doanh. Các môn học nhấn mạnh ứng dụng thực tiễn, với các kỳ thực tập và tham quan doanh nghiệp từ năm thứ nhất. Chương trình cũng phát triển kỹ năng giao tiếp, làm việc nhóm và khả năng thích nghi với xu hướng công nghệ. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ tư vấn và triển khai giải pháp hệ thống thông tin, đến quản trị cơ sở dữ liệu và phân tích dữ liệu. Sinh viên có thể làm việc tại các doanh nghiệp lớn, đảm nhận vai trò quản trị dự án CNTT hoặc tư vấn chiến lược công nghệ. Với nhu cầu cao về nhân lực CNTT, 100% sinh viên có việc làm trong 6 tháng sau tốt nghiệp, trong đó hơn 90% làm đúng ngành. Chuyên ngành này phù hợp với những ai yêu thích công nghệ và có khả năng tổ chức tốt. Chương trình đào tạo được thiết kế đặc thù, với sự tham gia của các chuyên gia từ doanh nghiệp uy tín, giúp sinh viên tiếp cận nhanh với thị trường lao động. Sinh viên tốt nghiệp có thể đảm nhận các vai trò quan trọng trong việc nâng cao hiệu quả quản lý và kinh doanh thông minh.
________________


Chunk 27: Trí tuệ nhân tạo trong kinh doanh (Mã ngành: 7340405)
Chuyên ngành Trí tuệ nhân tạo trong kinh doanh, thuộc ngành Hệ thống thông tin quản lý, đào tạo cử nhân với kiến thức nền tảng về quản trị và chuyên sâu về trí tuệ nhân tạo (AI), đáp ứng xu hướng chuyển đổi số toàn cầu. Chương trình cung cấp kỹ năng phát triển và triển khai giải pháp AI, tích hợp công nghệ vào hệ thống kinh doanh và phân tích dữ liệu lớn. Sinh viên được rèn luyện tư duy sáng tạo, khả năng lập trình và quản trị hệ thống thông minh. Các môn học nhấn mạnh ứng dụng thực tiễn, với các dự án thực tế và kỳ thực tập tại doanh nghiệp. Chương trình cũng phát triển kỹ năng giao tiếp, làm việc nhóm và khả năng thích nghi với công nghệ mới. Cơ hội nghề nghiệp của chuyên ngành này rất phong phú, từ chuyên viên tư vấn AI, phát triển hệ thống, đến kỹ sư dữ liệu và chuyên viên phân tích dữ liệu. Sinh viên có thể làm việc tại các công ty công nghệ, doanh nghiệp lớn, hoặc nghiên cứu và giảng dạy tại các trường đại học. Các vị trí đảm bảo an ninh dữ liệu hoặc phát triển sản phẩm AI cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai đam mê công nghệ và muốn dẫn đầu trong thời đại số hóa. Với nhu cầu cao về nhân lực AI, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa. Chương trình đào tạo cung cấp nền tảng vững chắc, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc đổi mới và nâng cao hiệu quả kinh doanh. Sinh viên có thể tiếp tục học cao học trong các lĩnh vực như khoa học máy tính, quản trị kinh doanh hoặc hệ thống thông tin.
________________


Chunk 28: Khoa học dữ liệu và phân tích kinh doanh (Mã ngành: 7460108)
Chuyên ngành Khoa học dữ liệu và phân tích kinh doanh, thuộc ngành Khoa học dữ liệu, đào tạo cử nhân với năng lực quản trị, khai thác và phân tích dữ liệu, hỗ trợ ra quyết định kinh doanh trong thời đại công nghiệp 4.0. Chương trình cung cấp kiến thức chuyên sâu về phân tích thị trường, dự báo tài chính và phân tích dữ liệu khách hàng, kết hợp với kỹ năng sử dụng công nghệ như AI, Big Data và IoT. Sinh viên được rèn luyện tư duy phân tích, khả năng lập trình và quản trị cơ sở dữ liệu. Các môn học nhấn mạnh ứng dụng thực tiễn, với các dự án thực tế và kỳ thực tập tại doanh nghiệp. Chương trình cũng phát triển kỹ năng giao tiếp, làm việc nhóm và khả năng thích nghi với môi trường số hóa. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ chuyên viên quản trị cơ sở dữ liệu, phân tích dữ liệu lớn, đến chuyên viên nghiên cứu thị trường và tư vấn kinh doanh. Sinh viên có thể làm việc tại các doanh nghiệp, tổ chức kinh tế - xã hội, hoặc khởi nghiệp trong lĩnh vực công nghệ số. Sau 5 năm, sinh viên có thể đảm nhận các vai trò như giám đốc dữ liệu hoặc phụ trách hệ thống thông tin doanh nghiệp. Chuyên ngành này phù hợp với những ai yêu thích làm việc với dữ liệu và có tư duy logic. Với nhu cầu cao về nhân lực khoa học dữ liệu, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa. Chương trình đào tạo cung cấp nền tảng kiến thức hiện đại, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc tối ưu hóa quyết định kinh doanh và nâng cao năng lực cạnh tranh.
________________


Chunk 29: Luật học (Mã ngành: 7380101)
Chuyên ngành Luật học, thuộc ngành Luật, đào tạo cử nhân với kiến thức tổng quát về hệ thống pháp luật Việt Nam và quốc tế, đáp ứng nhu cầu nhân lực trong môi trường hội nhập. Chương trình cung cấp nền tảng vững chắc về pháp luật dân sự, hành chính, quyền con người và kinh doanh, kết hợp với kỹ năng sử dụng công nghệ thông tin và phần mềm chuyên dụng. Sinh viên được rèn luyện tư duy phân tích, khả năng áp dụng pháp luật và giao tiếp hiệu quả. Các môn học nhấn mạnh ứng dụng thực tiễn, chuẩn bị cho sinh viên làm việc trong các cơ quan nhà nước và tổ chức quốc tế. Chương trình cũng chú trọng đạo đức nghề nghiệp và năng lực học tập suốt đời. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ công tác quản lý, thanh tra, pháp chế, đến thẩm phán, kiểm sát viên và luật sư tư vấn. Sinh viên có thể làm việc tại các văn phòng luật sư, công chứng, hoặc các doanh nghiệp với vai trò chuyên viên pháp lý. Các vị trí tại trung tâm tài chính và khu thương mại tự do Đà Nẵng cũng là lựa chọn tiềm năng. Ngoài ra, sinh viên có thể giảng dạy và nghiên cứu tại các trường đại học hoặc làm việc tại các tổ chức quốc tế. Chuyên ngành này phù hợp với những ai yêu thích pháp luật và có khả năng tư duy logic. Với nhu cầu cao về nhân lực pháp lý, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa. Chương trình đào tạo cung cấp nền tảng kiến thức toàn diện, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc thực thi và bảo vệ pháp luật.
________________


Chunk 30: Luật kinh doanh (Mã ngành: 7380107)
Chuyên ngành Luật kinh doanh, thuộc ngành Luật kinh tế, đào tạo cử nhân với kiến thức chuyên sâu về pháp luật kinh doanh, đáp ứng nhu cầu nhân lực trong thời kỳ chuyển đổi số và hội nhập quốc tế. Chương trình cung cấp nền tảng vững chắc về pháp luật Việt Nam và quốc tế, kết hợp với kỹ năng áp dụng pháp luật vào thực tiễn kinh doanh. Sinh viên được rèn luyện tư duy phân tích, khả năng tư vấn pháp lý và giao tiếp hiệu quả. Các môn học nhấn mạnh ứng dụng thực tiễn, chuẩn bị cho sinh viên làm việc trong các doanh nghiệp và cơ quan nhà nước. Chương trình cũng phát triển kỹ năng ngoại ngữ, tin học và đạo đức nghề nghiệp. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ chuyên viên pháp chế, nhân viên hành chính, đến luật sư hoặc chuyên viên công chứng tại các văn phòng luật sư. Sinh viên có thể làm việc tại các cơ quan quản lý nhà nước, tổ chức tín dụng, hoặc đảm nhận vai trò trưởng bộ phận pháp chế, giám đốc doanh nghiệp. Các vị trí tại trung tâm tài chính quốc tế Đà Nẵng cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai yêu thích pháp luật và có khả năng tư duy chiến lược. Với nhu cầu cao về nhân lực pháp lý trong kinh doanh, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa. Chương trình đào tạo cung cấp nền tảng kiến thức toàn diện, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc tư vấn và quản lý pháp lý, góp phần nâng cao hiệu quả kinh doanh.
________________


Chunk 31: Luật thương mại quốc tế (Mã ngành: 7380107)
Chuyên ngành Luật thương mại quốc tế, thuộc ngành Luật kinh tế, đào tạo cử nhân với kiến thức chuyên sâu về pháp luật thương mại quốc tế, đáp ứng nhu cầu nhân lực trong thời kỳ hội nhập và chuyển đổi số. Chương trình, với tùy chọn bán phần tiếng Anh, cung cấp nền tảng vững chắc về pháp luật Việt Nam và quốc tế, kết hợp với kỹ năng tư vấn pháp lý và đàm phán quốc tế. Sinh viên được rèn luyện khả năng sử dụng ngoại ngữ, phân tích pháp lý và giao tiếp hiệu quả trong môi trường toàn cầu. Các môn học nhấn mạnh ứng dụng thực tiễn, chuẩn bị cho sinh viên làm việc tại các doanh nghiệp đa quốc gia và tổ chức quốc tế. Chương trình cũng chú trọng đạo đức nghề nghiệp và năng lực học tập suốt đời. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ chuyên viên pháp chế, tư vấn luật thương mại quốc tế, đến luật sư hoặc trọng tài viên. Sinh viên có thể làm việc tại các cơ quan quản lý nhà nước, hiệp hội thương mại, hoặc các vị trí ngoại giao liên quan đến kinh tế. Các vai trò tại trung tâm tài chính và khu thương mại tự do Đà Nẵng cũng là triển vọng hấp dẫn. Chuyên ngành này phù hợp với những ai yêu thích pháp luật và có kỹ năng ngoại ngữ tốt. Với nhu cầu cao về nhân lực pháp lý quốc tế, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa. Chương trình đào tạo cung cấp nền tảng kiến thức hiện đại, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc xử lý các vấn đề pháp lý thương mại toàn cầu.
________________


Chunk 32: Quản trị kinh doanh du lịch (Mã ngành: 7810103)
Chuyên ngành Quản trị kinh doanh du lịch, thuộc ngành Quản trị dịch vụ du lịch và lữ hành, đào tạo cử nhân với năng lực chuyên môn trong quản trị doanh nghiệp du lịch và phục vụ khách trong môi trường toàn cầu. Chương trình cung cấp kiến thức về tổ chức tour, marketing du lịch và quản lý lữ hành, kết hợp với kỹ năng giao tiếp, ngoại ngữ và tin học. Sinh viên được rèn luyện tư duy sáng tạo, khả năng làm việc nhóm và thích nghi với xu hướng du lịch hiện đại. Các môn học nhấn mạnh ứng dụng thực tiễn, với các chuyến thực tế và kỳ thực tập tại các công ty du lịch. Chương trình cũng phát triển đạo đức nghề nghiệp và năng lực học tập suốt đời. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ nhân viên vận hành, lễ tân, đến chuyên viên marketing hoặc nhân sự trong các công ty du lịch. Sinh viên có thể làm việc tại các cơ sở lưu trú, trung tâm kinh doanh du lịch, hoặc các cơ quan quản lý du lịch. Các vị trí nghiên cứu và đào tạo về du lịch cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai yêu thích du lịch và có kỹ năng giao tiếp tốt. Với sự phát triển của ngành du lịch, nhu cầu nhân lực trong lĩnh vực này ngày càng tăng. Chương trình đào tạo tích cực, kích thích tư duy sáng tạo, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc nâng cao trải nghiệm khách hàng và phát triển ngành du lịch.
________________


Chunk 33: Quản trị sự kiện (Mã ngành: 7810103)
Chuyên ngành Quản trị sự kiện, thuộc ngành Quản trị dịch vụ du lịch và lữ hành, đào tạo cử nhân với năng lực tổ chức sự kiện và quản trị doanh nghiệp sự kiện trong môi trường đa văn hóa và công nghệ 4.0. Chương trình cung cấp kiến thức về lập kế hoạch sự kiện, marketing sự kiện và quản lý tài trợ, kết hợp với kỹ năng giao tiếp, ngoại ngữ và tư duy phản biện. Sinh viên được rèn luyện khả năng sáng tạo, làm việc nhóm và thích nghi với xu hướng đổi mới. Các môn học nhấn mạnh ứng dụng thực tiễn, với các dự án thực tế và kỳ thực tập tại các công ty tổ chức sự kiện. Chương trình cũng phát triển đạo đức nghề nghiệp và năng lực học tập suốt đời. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ nhân viên tổ chức sự kiện, chuyên viên marketing sự kiện, đến nhân viên PR nội bộ trong các doanh nghiệp. Sinh viên có thể làm việc tại các trung tâm sự kiện du lịch hoặc các công ty du lịch có chức năng tổ chức sự kiện. Các vị trí nghiên cứu và đào tạo về kinh doanh du lịch cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai yêu thích sáng tạo và có kỹ năng tổ chức tốt. Với nhu cầu ngày càng cao về tổ chức sự kiện chuyên nghiệp, sinh viên tốt nghiệp có triển vọng nghề nghiệp sáng sủa. Chương trình đào tạo tích cực, với các hoạt động ngoại khóa giúp rèn luyện kỹ năng mềm, đảm bảo sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong ngành sự kiện.
________________


Chunk 34: Quản trị khách sạn (Mã ngành: 7810201)
Chuyên ngành Quản trị khách sạn, thuộc ngành Quản trị khách sạn, đào tạo cử nhân với năng lực chuyên môn trong quản trị cơ sở lưu trú và phục vụ khách du lịch trong môi trường toàn cầu hóa. Chương trình cung cấp kiến thức về vận hành khách sạn, marketing, tài chính và nhân sự, kết hợp với kỹ năng giao tiếp, ngoại ngữ và tin học. Sinh viên được rèn luyện tư duy phản biện, khả năng sáng tạo và thích nghi với xu hướng kinh doanh hiện đại. Các môn học nhấn mạnh ứng dụng thực tiễn, với các kỳ thực tập và tham quan thực tế tại các khách sạn trong và ngoài nước. Chương trình cũng phát triển đạo đức nghề nghiệp và năng lực học tập suốt đời. Cơ hội nghề nghiệp của chuyên ngành này rất đa dạng, từ nhân viên lễ tân, phục vụ nhà hàng, đến chuyên viên trong các phòng ban như marketing, nhân sự hoặc tài chính. Sinh viên có thể làm việc tại các khách sạn quốc tế, trung tâm kinh doanh du lịch, hoặc các cơ quan quản lý du lịch. Các vị trí nghiên cứu và đào tạo về du lịch cũng là lựa chọn tiềm năng. Chuyên ngành này phù hợp với những ai yêu thích dịch vụ khách hàng và có kỹ năng tổ chức tốt. Với sự phát triển của ngành du lịch và khách sạn, nhu cầu nhân lực trong lĩnh vực này ngày càng tăng. Chương trình đào tạo tích cực, thúc đẩy sự sáng tạo và kỹ năng ra quyết định, giúp sinh viên sẵn sàng đảm nhận các vai trò quan trọng trong việc nâng cao trải nghiệm khách hàng và quản lý hiệu quả các cơ sở lưu trú.
'''

# FastAPI setup
app = FastAPI(title="DUE LLM Chat API", description="API trả lời từ file Chuyen Nganh.txt bằng LLM (full context)", version="2.2.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class QueryRequest(BaseModel):
    query: str

class QueryResponse(BaseModel):
    answer: str
    timestamp: Optional[str] = None
    sender: str = "bot"
    message: Optional[str] = None

@app.get("/")
async def root():
    return {"message": "DUE LLM Chat API is running (full context)"}

@app.post("/query", response_model=QueryResponse)
async def process_query(query_request: QueryRequest, request: Request):
    # Đưa toàn bộ context vào prompt
    system_prompt = (
        "Bạn là một trợ lý AI của trường Đại học Kinh tế - Đại học Đà Nẵng. "
        "Hãy trả lời câu hỏi dựa trên thông tin context dưới đây. "
        "Nếu không tìm thấy thông tin, hãy nói bạn không có dữ liệu phù hợp. Trả lời bằng tiếng Việt tự nhiên."
    )
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": f"Context:\n{full_context}\n\nCâu hỏi: {query_request.query.strip()}"}
    ]
    # Gọi OpenAI Chat Completion
    try:
        response = client.chat.completions.create(
            model="gpt-4.1-nano",
            messages=messages,
            temperature=0.7,
            max_tokens=500
        )
        answer = response.choices[0].message.content.strip()
    except Exception as e:
        answer = f"Lỗi khi gọi LLM: {str(e)}"
    timestamp = datetime.now().strftime("%H:%M:%S")
    return QueryResponse(answer=answer, timestamp=timestamp, sender="bot", message=answer)

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000) 