services:
  - type: web
    name: career-advisor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn Mainver2:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false 